name: 'Trivy Sarif Upload'
description: 'Run Trivy and upload sarif results to GitHub Security tab.'
author: 'RoseSecurity'

branding:
  icon: 'cloud'
  color: 'purple'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
    default: ${{ github.token }}
  working_directory:
    description: |
      Directory to run the action on, from the repo root.
      Default is . (root of the repository)
    default: '.'
    required: false
  trivy_command:
    description: |
      Trivy command [aws,config,filesystem,image,kubernetes,rootfs,sbom,vm]
    required: true
    default: 'config'
  trivy_version:
    description: |
      The version of trivy to install.
      Default is latest.
    default: 'latest'
    required: false
  trivy_flags:
    description: |
      List of arguments to send to trivy
      For the output to be parsable by reviewdog --format=checkstyle is enforced
      Default is blank.
    default: ''
    required: false

outputs:
  trivy-return-code:
    description: 'trivy command return code'
    value: ${{ steps.trivy.outputs.trivy-return-code }}

runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      id: trivy
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working_directory }}
        INPUT_TRIVY_VERSION: ${{ inputs.trivy_version }}
        INPUT_TRIVY_COMMAND: ${{ inputs.trivy_command }}
        INPUT_TRIVY_TARGET: ${{ inputs.trivy_target }}
        INPUT_TRIVY_FLAGS: ${{ inputs.trivy_flags }}

    - name: Upload trivy Sarif Findings
      id: upload
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ github.workspace }}/trivy-results.sarif
      if: always()
